### PR TITLE
Modify cmake build

### PR DESCRIPTION
**Pull request by leej3**
Supercedes #4

### CODE REVIEW

**Comment by leej3** [comment]
Resolves #1.

Still need to consider package version and .so versions.

**Comment by hjmjohnson** [comment]
@leej3 Is this still a WIP?  Let me know when it is ready for final consideration.

**Comment by leej3** [comment]
It is still WIP. I want to do some tidying up/improvements based on insights from the nifti_clib work. Will do

**Comment by leej3** [comment]
I think this is good to go. 

Currently I am manually installing nifti_clib from my branch on circleci. That can be switched too master before merging this (and subsequently to an apt-get install).

This, along with https://github.com/NIFTI-Imaging/nifti_clib/pull/62, now builds with ITK (Cmake v3.10.2 if DOWNLOAD_TEST_DATA is set to OFF).

**Comment by leej3** [comment]
Also, @hjmjohnson, I'm not tied to circleci. I'm just more used to that (the local cli works great). I'm not as familiar with the travis/cdash setup but if that's desirable we could replace the circleci stuff with that.

**Review by hjmjohnson — APPROVED** [review]
Looks correct to me on quick review.

**Comment by leej3** [comment]
ok thanks. a hiccup with the tests. I'll fix that an merge it.

**Pull request merged**
