### PR TITLE
add some basic tests

### PR DESCRIPTION
**Pull request by leej3**

### CODE REVIEW

**Comment by leej3** [comment]
@hjmjohnson, do you have time to take a look at this? Is it ok to merge? I wanted to begin the process of adding tests before merging #4. The few tests I have added run fine. And cpack now works for .deb and compressed source. I've copied across content from the nifti repo for the dashboard but don't know my way around setting up the dashboard, haven't added the travis.yml because I'm not sure what parameters we wish to test, and I'm  not sure what the packaging directory is required for.

**Comment by hjmjohnson** [comment]
@leej3 The general convention is that anything with a "WIP" means that by definition (work in progress) it is not ready for review or acceptance.

WIP's indicate that more work is known to exist before it is ready for review.

Additionally, I am not assigned as a reviewer.  I you want be to look at a PR like this, 1) I need to be listed as a reviewer, 2) The WIP prefix needs to be changed, and 3) more documentation should be added to the commit message.  Basically everything in the comment from 7 minutes about would be be nice to have had in the commit message (in a more formal tone rather than a personal note) that persists in the repository for years.

**Comment by hjmjohnson** [comment]
@leej3 I don't have much experience with gifts.  your changes look fine to me, after my previous recommendations are addressed.

**Comment by leej3** [comment]
Thanks for the pointers. That's done now.

**Pull request merged**
